server:
  port: 8080

spring:
  application:
    name: order-service

shipping:
  api:
    base-url: ${SHIPPING_API_BASE_URL:http://localhost:8081}

resilience4j:
  circuitbreaker:
    instances:
      shippingClient:
        sliding-window-type: TIME_BASED
        sliding-window-size: 30
        minimum-number-of-calls: 5
        failure-rate-threshold: 1
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always

